name: hangups
version: git
version-script: git describe --dirty | cut -c 2-
summary: Third-party instant messaging client for Google Hangouts
description: |
  hangups is a third-party instant messaging client for Google Hangouts with a
  text-based user interface.
confinement: strict
grade: stable
base: core18

apps:
  hangups:
    command: bin/hangups
    plugs:
        - network
    # force aiohttp to use certifi (like requests does), because the core18
    # base does not include ca certificates
    environment:
        SSL_CERT_FILE: /snap/hangups/current/lib/python3.6/site-packages/certifi/cacert.pem

parts:
  hangups:
    plugin: python
    source: .
